apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-service
spec:
  selector:
    matchLabels:
      run: eureka-service
  replicas: 1
  template:
    metadata:
      labels:
        run: eureka-service
    spec:
      containers:
      - name: eureka-service
        image: apacpoc.azurecr.io/eureka-service:0.0.1-SNAPSHOT
        ports:
        - containerPort: 8761